version: "3"

services:
  game:
    build: .
    volumes:
      - ./Server/lib:/app/Server/lib/
    depends_on:
      - db
    command: [ "node", "/app/Server/lib/Game/cluster.js", "0", "1" ]
    restart: always
    networks:
      network:
        ipv4_address: 172.30.0.2
  web:
    build: .
    volumes:
      - ./Server/lib:/app/Server/lib/
      - kkutu_data:/kkutu
    command: [ "node", "/app/Server/lib/Web/cluster.js", "1" ]
    restart: always
    depends_on:
      - db
      - game
    ports:
      - 3100:80
    networks:
      network:
        ipv4_address: 172.30.0.3
  db:
    build:
      context: .
      dockerfile: ./psql.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 172.30.0.4
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    networks:
      network:
        ipv4_address: 172.30.0.5

networks:
  network:
    external: true
    driver: bridge
    name: kkutu_network

volumes:
  kkutu_data:
  db_data:
